# Generated by Django 5.0.7 on 2024-07-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=60)),
                ('course', models.CharField(max_length=30)),
                ('batch', models.IntegerField()),
            ],
        ),
    ]
